#development:
#  adapter: mysql2
#  encoding: utf8
#  database: ivcrcdb_development
#  username: root
#  password: Raxe9too
#  socket: /var/mysql/mysql.sock
#
#test: &test
#  adapter: mysql2
#  encoding: utf8
#  database: ivcrcdb_test
#  username: root
#  password: Raxe9too
#  socket: /var/mysql/mysql.sock
#
#cucumber:
#  <<: *test

development:
  adapter: postgresql
  encoding: utf8
  database: ivcrcdb
  pool: 5
  username: postgres
  password: 123456

production:
  adapter: postgresql
  encoding: utf8
  database: ivcrcdb
  pool: 5
  username: postgres
  password: 123456