development:
  adapter: postgresql
  encoding: utf8
  database: ivcrcdb
  pool: 5
  username: postgres
  password: 123456

production:
  adapter: postgresql
  encoding: utf8
  database: ivcrcdb
  pool: 5
  username: postgres
  password: 123456